Use ogre-package submodule

diff --git a/fetch-deps b/fetch-deps
--- a/fetch-deps
+++ b/fetch-deps
@@ -56,7 +56,6 @@ done
 
 INSTALL_SNAPCRAFT=false
 
-CGAL_MANUAL_BUILD=false
 OGRE_MANUAL_BUILD=false
 
 if [ $OSTYPE == "linux-gnu" ]; then
@@ -85,22 +84,35 @@ if [ $OSTYPE == "linux-gnu" ]; then
 
         #CODENAME=`lsb_release --codename | cut -f2`
         INSTALLSYSTEM=${INSTALLSYSTEMS[$APTGET]}
-        PACKAGES="cmake git pkg-config build-essential libx11-dev libgl1-mesa-dev libxrandr-dev libxt-dev libxaw7-dev uuid-dev libboost-all-dev libssl-dev libopenal-dev zlib1g-dev libfreetype6-dev libfreeimage-dev libcgal-dev libsdl2-dev clang-format snapd rapidjson-dev liblua5.3-dev"
+        PACKAGES="cmake git pkg-config build-essential uuid-dev libboost-all-dev libssl-dev libopenal-dev libcgal-dev libsdl2-dev clang-format snapd rapidjson-dev liblua5.3-dev"
         OGRE_MANUAL_BUILD=true
         INSTALL_SNAPCRAFT=true
     else
         printf " $CROSSMARK Your distribution '$DISTRO' is not supported. Aborting. \e[91mYou may have to install all dependencies manually.\e[0m\n"
+        exit 1 
     fi
 elif [[ $MACOS == true ]]; then
     # macOS
-    printf " $CHECKMARK macOS is supported\n"
+    printf " $CHECKMARK macOS is supported.\n"
     
     INSTALLSYSTEM=${INSTALLSYSTEMS[$HOMEBREW]}
     PACKAGES=(cmake boost cgal zlib openssl openal-soft freeimage freetype sdl2 clang-format rapidjson lua)
     OGRE_MANUAL_BUILD=true
 else
     printf " $CROSSMARK Your OS '$OSTYPE' is not supported. Aborting. \e[91mYou may have to install all dependencies manually.\e[0m\n"
+    exit 1 
 fi
+
+
+
+
+# Cleanup and sync submodules
+if [ ! -d thirdparty/ogre-package/ogre/Components/Overlay/src/imgui ]; then
+    rm -R thirdparty/ogre-package/ogre/Components/Overlay/src/imgui
+    git -C thirdparty/ogre-package/ogre reset --hard
+fi
+git submodule sync
+git submodule update --init --recursive --remote
 
 
 
@@ -149,24 +161,6 @@ if [ $INSTALLSYSTEM ]; then
 
     if [ $INSTALL_SNAPCRAFT = true ]; then
         command -v snapcraft >/dev/null 2>&1 || { sudo snap install --classic snapcraft; }
-    fi
-
-    if [ $CGAL_MANUAL_BUILD = true ]; then
-        printf "$LINEBG Building CGAL...\n"
-        CGAL_VERSION="5.0"
-        mkdir -p thirdparty/manual-build/lib
-        cd thirdparty/manual-build/lib
-        rm -rf CGAL-*
-        wget https://github.com/CGAL/cgal/releases/download/releases/CGAL-$CGAL_VERSION/CGAL-$CGAL_VERSION.zip
-        unzip CGAL-$CGAL_VERSION.zip
-        cd CGAL-$CGAL_VERSION
-        if [ -d build ]; then rm -Rf build; fi
-        mkdir build
-        cd build
-        cmake -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DCGAL_HEADER_ONLY=OFF -DWITH_CGAL_Qt5=OFF -DCMAKE_INSTALL_PREFIX="$CWD/thirdparty/manual-build/precompiled/cgal" -DWITH_Eigen3=ON -DCMAKE_BUILD_TYPE=Release ..
-        make
-        make install
-        cd $CWD
     fi
 
     if [ $OGRE_MANUAL_BUILD = true ]; then
